[theme]
base = "light"
primaryColor = "#8B5E3C"               # Marrom terroso (cor de destaque)
backgroundColor = "#F5F3EF"           # Bege claro (fundo principal)
secondaryBackgroundColor = "#EDEAE4"  # Bege mais escuro (fundo dos cards)
textColor = "#322821"                 # Marrom escuro (texto)
font = "sans serif"